spring:
  config:
    import: "optional:classpath:application-local.yml"
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/authdb
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000   # 24 hours in milliseconds